name: Scheduled Booking Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-pip python3-venv

      - name: Upgrade pip and install numpy first
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install numpy==1.24.4

      - name: Install other Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Setup Chrome for Selenium
        uses: browser-actions/setup-chrome@v1

      - name: Run scraper script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_FILE }}
        run: python scraper_opportunities.py
