name: Scheduled Booking Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-pip

      - name: Upgrade pip, setuptools, wheel and install numpy from wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --only-binary=:all: numpy==1.24.4

      - name: Install other Python dependencies without dependencies (to avoid reinstalling numpy)
        run: |
          pip install -r requirements.txt --no-deps
          pip install pandas-gbq pydata-google-auth charset-normalizer


      - name: Setup Chrome for Selenium
        uses: browser-actions/setup-chrome@v1

      - name: Create Google Services JSON File
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json

      - name: Check JSON validity
        run: |
          python -c "import json; json.load(open('google-services.json'))"

      - name: Run scraper script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google-services.json
        run: python scraper_opportunities.py
