name: Scheduled Booking Scraper

on:
  schedule:
    # Runs every day at 6:00 UTC (adjust as needed)
    - cron: '0 6 * * *'

  workflow_dispatch:  # Manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome for Selenium
        uses: browser-actions/setup-chrome@v1

      - name: Run scraper script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_FILE }}
        run: python scraper_opportunities.py
